let vanDescription = "Awesome!";
let vanRainCouver = true;
let vanPopulation = 2581000;
let vanHockeyTeam = "Cannucks";
let vanLifestyle = undefined;
let vanHousing = null;
console.log('vanDescription' , vanDescription);
console.log('vanRainCouver' , vanRainCouver);
console.log('vanPopulation' , vanPopulation);
console.log('vanHockeyTeam' , vanHockeyTeam);
console.log('vanLifestyle' , vanLifestyle);
console.log('vanHousing' , vanHousing);
console.log('vanDescription' , typeof vanDescription);
console.log('vanRainCouver' , typeof vanRainCouver);
console.log('vanPopulation' , typeof vanPopulation);
console.log('vanHockeyTeam' , typeof vanHockeyTeam);
console.log('vanLifestyle' , typeof vanLifestyle);
console.log('vanHousing' , typeof vanHousing);
