let firstName = "Jason";
let lastName = "Chiu";
let age = 18;
let address = "richmond";
let dateOfBirth = "02/26/2018";
console.log ("First name: ", firstName);
console.log ("Last name:", lastName);
console.log ("Age:", age);
console.log ("Address:", address);
console.log ("Date of Birth:", dateOfBirth);